export const ADD_FORTNIGHTLY_PROFIT_REQUEST = 'ADD_FORTNIGHTLY_PROFIT_REQUEST';
export const ADD_FORTNIGHTLY_PROFIT_SUCCESS = 'ADD_FORTNIGHTLY_PROFIT_SUCCESS';
export const ADD_FORTNIGHTLY_PROFIT_FAIL = 'ADD_FORTNIGHTLY_PROFIT_FAIL';

export const VIEW_Admin_INCENTIVE_DATA_REQUEST = 'VIEW_Admin_INCENTIVE_DATA_REQUEST';
export const VIEW_Admin_INCENTIVE_DATA_SUCCESS = 'VIEW_Admin_INCENTIVE_DATA_SUCCESS';
export const VIEW_Admin_INCENTIVE_DATA_FAIL = 'VIEW_Admin_INCENTIVE_DATA_FAIL';

export const VIEW_Admin_FORTNIGHTLY_DATA_REQUEST = 'VIEW_Admin_FORTNIGHTLY_DATA_REQUEST';
export const VIEW_Admin_FORTNIGHTLY_DATA_SUCCESS = 'VIEW_Admin_FORTNIGHTLY_DATA_SUCCESS';
export const VIEW_Admin_FORTNIGHTLY_DATA_FAIL = 'VIEW_Admin_FORTNIGHTLY_DATA_FAIL';

export const VIEW_REFERRAL_DATA_REQUEST = 'VIEW_REFERRAL_DATA_REQUEST';
export const VIEW_REFERRAL_DATA_SUCCESS = 'VIEW_REFERRAL_DATA_SUCCESS';
export const VIEW_REFERRAL_DATA_FAIL = 'VIEW_REFERRAL_DATA_FAIL';

export const VIEW_Incentive_DATA_REQUEST = 'VIEW_Incentive_DATA_REQUEST';
export const VIEW_Incentive_DATA_SUCCESS = 'VIEW_Incentive_DATA_SUCCESS';
export const VIEW_Incentive_DATA_FAIL = 'VIEW_Incentive_DATA_FAIL';

export const VIEW_Fortnightly_DATA_REQUEST = 'VIEW_Fortnightly_DATA_REQUEST';
export const VIEW_Fortnightly_DATA_SUCCESS = 'VIEW_Fortnightly_DATA_SUCCESS';
export const VIEW_Fortnightly_DATA_FAIL = 'VIEW_Fortnightly_DATA_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
