// Trader action types
export const REQUEST_TRADER_ACCOUNT = 'REQUEST_TRADER_ACCOUNT';
export const REQUEST_TRADER_ACCOUNT_SUCCESS = 'REQUEST_TRADER_ACCOUNT_SUCCESS';
export const REQUEST_TRADER_ACCOUNT_FAIL = 'REQUEST_TRADER_ACCOUNT_FAIL';

export const GET_TRADER_REQUESTS = 'GET_TRADER_REQUESTS';
export const GET_TRADER_REQUESTS_SUCCESS = 'GET_TRADER_REQUESTS_SUCCESS';
export const GET_TRADER_REQUESTS_FAIL = 'GET_TRADER_REQUESTS_FAIL';

export const UPDATE_VERIFICATION_STATUS = 'UPDATE_VERIFICATION_STATUS';
export const UPDATE_VERIFICATION_STATUS_SUCCESS = 'UPDATE_VERIFICATION_STATUS_SUCCESS';
export const UPDATE_VERIFICATION_STATUS_FAIL = 'UPDATE_VERIFICATION_STATUS_FAIL';

export const GET_TRADER_ACCOUNT_STATUS = 'GET_TRADER_ACCOUNT_STATUS';
export const GET_TRADER_ACCOUNT_STATUS_SUCCESS = 'GET_TRADER_ACCOUNT_STATUS_SUCCESS';
export const GET_TRADER_ACCOUNT_STATUS_FAIL = 'GET_TRADER_ACCOUNT_STATUS_FAIL';


// Action Type for Clearing Errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
